plugins {
    id 'com.android.library'
}

android {
    namespace 'com.jaredrummler.android.colorpicker'
    compileSdk 36
    resourcePrefix 'cpv_'

    defaultConfig {
        minSdk 21
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.core:core:1.17.0'
}
